// only a front-end app, so store grid content in the front directly
// should be moved to the back later when the back will be created and used
export const grid: string[][] = [
    ["E", "P", "I", "C", "E", "A", "S", "0", "M", "E", "R", "0", "O", "T", "E"],
    ["R", "O", "M", "A", "N", "0", "O", "T", "A", "R", "I", "E", "0", "R", "U"],
    ["U", "S", "A", "N", "T", "0", "U", "B", "U", "E", "S", "Q", "U", "E", "0"],
    ["P", "A", "G", "A", "I", "E", "S", "0", "L", "I", "Q", "U", "E", "U", "R"],
    ["T", "0", "E", "D", "E", "N", "T", "E", "0", "N", "U", "I", "0", "I", "0"],
    ["I", "N", "0", "A", "R", "0", "R", "A", "0", "T", "E", "P", "A", "L", "E"],
    ["O", "U", "I", "0", "S", "E", "A", "U", "0", "E", "R", "E", "0", "L", "R"],
    ["N", "A", "S", "A", "0", "C", "I", "0", "F", "S", "0", "R", "I", "E", "N"],
    ["0", "N", "O", "0", "O", "U", "R", "A", "L", "0", "P", "0", "G", "R", "E"],
    ["E", "C", "L", "I", "P", "S", "E", "0", "0", "F", "R", "0", "N", "0", "S"],
    ["G", "E", "A", "N", "T", "S", "0", "C", "E", "L", "E", "R", "I", "0", "T"],
    ["L", "0", "N", "0", "E", "O", "L", "I", "E", "N", "S", "0", "T", "D", "0"],
    ["I", "N", "T", "E", "R", "N", "A", "T", "0", "0", "I", "0", "I", "E", "F"],
    ["S", "I", "E", "N", "0", "0", "V", "E", "L", "O", "D", "R", "O", "M", "E"],
    ["E", "N", "S", "A", "C", "H", "E", "R", "0", "H", "E", "R", "N", "I", "E"],
  ];
  
  export const def = [
    { word: "", definition: "" },
    { word: "EPICEAS", definition: "Épicettes outre-Atlantique" },
    { word: "MER", definition: "Elle peut être morte mais pas par noyade" },
    { word: "OTE", definition: "Enlève" },
    { word: "RU", definition: "Ça coule de source" },
    { word: "OTARIE", definition: "Son petit est le chiot" },
    { word: "UBUESQUE", definition: "Absurde comme un roi" },
    { word: "EU", definition: "Europium" },
    { word: "USANT", definition: "Crevant" },
    { word: "PAGAIES", definition: "Rames sans sourire" },
    { word: "TB", definition: "C'est mieux que bien" },
    { word: "LIQUEUR", definition: "Sirop à consommer avec modération" },
    { word: "ROMAN", definition: "Entre latin et français" },
    { word: "POSA", definition: "Fit le beau" },
    { word: "EDENTE", definition: "A pris un bon coup dans la bouche" },
    { word: "MAUL", definition: "Pack emmêlé" },
    { word: "NUI", definition: "À l'origine de la nuisance" },
    { word: "UE", definition: "Groupe de pays" },
    { word: "IN", definition: "À la mode" },
    { word: "IMAGE", definition: "On y a le droit quand on est sage" },
    { word: "TEPALE", definition: "Partie d'une fleur" },
    { word: "OUI", definition: "À dire lors du mariage" },
    {
      word: "SEAU",
      definition: "Il n'a pas de garde mais il sert à construire des châteaux",
    },
    { word: "ERE", definition: "Ça fait quelques années" },
    { word: "LR", definition: "Parti français" },
    { word: "NASA", definition: "On y a la tête dans les étoiles" },
    { word: "CI", definition: "Souvent joint à un autre mot" },
    { word: "EAU", definition: "Dans 20 ou 30 ans, il n'y en aura plus" },
    { word: "FS", definition: "Femtoseconde" },
    { word: "RISQUER", definition: "Entreprendre" },
    { word: "RIEN", definition: "Ce qu'il s'est passé ici le 17 avril 1891" },
    {
      word: "ERUPTION",
      definition: "Elle peut être solaire, effusive ou cutanée",
    },
    { word: "NO", definition: "Nobélium" },
    { word: "OURAL", definition: "Frontière intercontinentale" },
    { word: "EREINTES", definition: "Brisés" },
    { word: "EQUIPER", definition: "Pourvoir de moyens" },
    { word: "GRE", definition: "Plein, il va à son insu" },
    { word: "ECLIPSE", definition: "Quand le Soleil est dans la Lune" },
    { word: "FL", definition: "Une tour à haute voix" },
    { word: "FR", definition: "Domaine national" },
    { word: "TREUILLER", definition: "Tirer à la corde" },
    { word: "GEANTS", definition: "De la route, ce sont des cyclistes" },
    { word: "CELERI", definition: "Persil des marais" },
    { word: "NUANCE", definition: "Petite différence" },
    { word: "EOLIENS", definition: "Se dit de parcs à énergie" },
    { word: "TD", definition: "Comme un TP mais sans pratique" },
    { word: "ERNEST", definition: "Le prénom pour qui sonne le glas" },
    { word: "INTERNAT", definition: "Le chirurgien y passe à un moment" },
    { word: "EE", definition: "Se pose dans le green" },
    { word: "FLN", definition: "Parti algérien" },
    { word: "IEF", definition: "Conclut un débrief" },
    { word: "SIEN", definition: "Pas à moi ni à toi" },
    { word: "OPTER", definition: "Trancher entre deux choses incompatibles" },
    { word: "VELODROME", definition: "Stade de foot provençal" },
    { word: "EGLISE", definition: "Il faut la remettre au milieu du village" },
    { word: "NIN", definition: "Ça finit toujours comme ça avec du venin" },
    { word: "ISOLANTES", definition: "Pas conductrices" },
    { word: "ENA", definition: "École fermée en 2021" },
    { word: "LAVE", definition: "Ça coule mais pas d'une source" },
    { word: "CITER", definition: "Plagier mais avec des sources" },
    { word: "ENSACHER", definition: "Mettre en sachet" },
    { word: "OH", definition: "Ion bien surprenant" },
    {
      word: "PRESIDE",
      definition: "Place de souveraineté comme Ceuta ou Melilla",
    },
    { word: "RR", definition: "Au centre de la Terre" },
    { word: "IGNITION", definition: "C'est le feu !!" },
    { word: "DEMI", definition: "Joueur ou bière" },
    { word: "HERNIE", definition: "Gonflement d'une chambre à air" },
    { word: "FEE", definition: "Sauve ou maudit les héros de conte" },
    { word: "CANADA", definition: "Pays de feuille et de sirop" },
    { word: "ENTIERS", definition: "À la fois entiers et complexes" },
    { word: "AR", definition: "Argon" },
    { word: "EN", definition: "Préposition signifiant à, dans, sur, de, comme" },
    { word: "ECUSSON", definition: "Symbole de famille" },
    {
      word: "RA",
      definition:
        "Changez sa deuxième lettre par une autre voyelle, c'est la même personne",
    },
    { word: "SOUSTRAIRE", definition: "Préserver de quelque chose" },
  ];
  